CREATE TABLE MEMBER(
    ID CHAR(8),
    NAME NVARCHAR2(10),
    ADDR NVARCHAR2(50),
    NATION NCHAR(4),
    EMAIL VARCHAR2(50),
    AGE NUMBER(7,2));

ALTER TABLE MEMBER ADD BIO VARCHAR2(20);
ALTER TABLE MEMBER MODIFY BIGO VARCHAR2(30);
ALTER TABLE MEMBER RENAME COLUMN BLGO TO REMARK;

DROP TABLE MEMBER;