CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;

--DEPT_TEMP2에 있는 LOC 모두 수정
UPDATE DEPT_TEMP2 SET LOC='SEOUL';

UPDATE DEPT_TEMP2 SET LOC='SEOUL' WHERE DEPTNO=10;



SELECT * FROM DEPT_TEMP2;
ROLLBACK;