--서브쿼리: 쿼리문 안에 다른 쿼리문을 포함하고 있는 상태
--단일행 서브쿼리
SELECT * FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='JONES');

--사원이름이 ALLEN인 사원의 추가수당보다 많이 받는 사원을 출력
SELECT * FROM emp WHERE COMM>(SELECT COMM FROM EMP WHERE ENAME='ALLEN');

--사원이름이 WARD인 사원의 입사일보다 빨리 입사한 사원을 출력
SELECT * FROM emp WHERE HIREDATE<(SELECT HIREDATE FROM EMP WHERE ENAME='WARD');

--20번 주서에 속한 사원 중 전체 사원의 평균급여보다 높은 급여를 받는 사원 출력
SELECT * FROM emp WHERE DEPTNO=20 AND sal>(SELECT AVG(SAL) FROM EMP);

--20번 주서에 속한 사원 중 전체 사원의 평균급여보다 높은 급여를 받는 사원 출력(부서명, 지역위치 출력)
SELECT * FROM emp E,dept D WHERE D.DEPTNO=E.DEPTNO AND D.DEPTNO=20 AND sal>(SELECT AVG(SAL) FROM EMP);

--다중행 서브쿼리

--서브쿼리 결과가 2개 이상 나오는 경우라면 단일행 서브쿼리의 연산자는 사용 불가
--단일 행하위 질의에 2개 이상의 행이 리턴되었습니다.
--SELECT * FROM EMP WHERE SAL >=(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

--IN
SELECT * FROM EMP WHERE SAL IN(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

--ANY(SOME)
-- =ANY : IN의 수행결과가 같게 나옴. 단, IN을 더 많이 사용함
SELECT * FROM EMP WHERE SAL = ANY(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
SELECT * FROM EMP WHERE SAL = SOME(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

--30번 부서 사원들의 최대급여보다 적은 급여를 받는 사원 출력
SELECT * FROM EMP WHERE SAL<ANY(SELECT MAX(SAL) FROM EMP WHERE DEPTNO=30);
SELECT * FROM EMP WHERE SAL<ANY(SELECT SAL FROM EMP WHERE DEPTNO=30);

--ALL : 서브쿼리의 결과를 모두 만족하는 메인쿼리를 추출할 때
--부서번호가 30번인 사원들의 최소급여보다 더 적은 급여를 받는 사원출력
SELECT * FROM EMP WHERE SAL < ALL (SELECT SAL FROM EMP WHERE DEPTNO=30);

--EXISTS : IN과 비슷한 개념, 단 IN보다 성능이 우수함
SELECT * FROM EMP WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO=20);
SELECT * FROM EMP WHERE NOT EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO=20);

SELECT EMPNO, DEPTNO FROM EMP WHERE EXISTS (SELECT DEPTNO FROM DEPT WHERE DEPTNO IN(20,30) AND EMP.DEPTNO=DEPT.DEPTNO);
SELECT EMPNO, DEPTNO FROM EMP WHERE NOT EXISTS (SELECT 1 FROM DEPT WHERE DEPTNO IN(20,30) AND EMP.DEPTNO=DEPT.DEPTNO);

--PPT 연습문제
--전체 사원중 ALLEN과 같은 직책인 사원들의 사원정보, 부서정보를 출력
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND E.JOB 
IN(SELECT JOB FROM EMP WHERE ENAME='ALLEN');

--전체 사원의 평균 급여보다 높은 급여를 받는 사원들의 사원정보, 부서정보, 급여등급정보 출력(단, 출력할때 급여가 많은순으로 정렬하되 같은경우에는 사원번호를 기준으로 오름차순)
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE FROM EMP E, DEPT D, SALGRADE S WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND E.SAL>(SELECT AVG(SAL) FROM EMP) ORDER BY E.SAL DESC, E.EMPNO ASC;

--다중 열 서브쿼리: 서브쿼리의 select 문에 비교할 컬럼이 여러개 나오는 방식
SELECT * FROM EMP WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO);

--FROM 절에 사용하는 서브쿼리(인라인 뷰)
SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC FROM (SELECT * FROM EMP WHERE DEPTNO=10) E, (SELECT * FROM DEPT) D
WHERE E.DEPTNO = D.DEPTNO;